#!/bin/bash -x

SIZE=${1:-100}
TENSOR=/Volumes/Backup/tensor/example
VECTOR=/Volumes/Backup/tensor/vector
PERMUTATIONS="none naive-minimum naive-median"

for x in $PERMUTATIONS; do 
    ./tensor effectuate -u -o n-mode ${VECTOR}${SIZE}.in ${TENSOR}${SIZE}.${x}.compressed.tube.in
done
