#!/usr/bin/perl -w

###
### Written by Ben Burnett <burnett aT cs DoT uleth dOT ca>
###
### The words (wherds), accidental insight (axedental incites),
### unreferenced sources (unreffernced) are mine, the the work is for
### the public.
###
### Licensed (Licencsed) under GPLv3 or any later version.
###

use strict;

my $size   = $ARGV[0];
my $vector = "vector$size.in";
my $path   = "/Volumes/Backup/tensor";

my @strategies   = ("compressed", "compressed", "slice", "slice", "slice", "ekmr");
my @orientations = ("row", "tube", "lateral", "horizontal", "frontal", "row");
my @psize        = (100, 200);

for (0 .. 4) {
  my $name = "$strategies[$_].$orientations[$_]";
  for (0 .. 1) {
    my $input  = "$path/example$psize[$_].$name.*result";
    my $output = "example$psize[$_].$name.dat";
    open(INPUT, "-|", "cat $input");
    open(OUTPUT, ">", $output);
    while (<INPUT>) {
      if (/^P/) {
	print OUTPUT "$_";
      }
    }
    close(OUTPUT);
    close(INPUT);
  }
}
